### ISSUE TITLE
Is card-reveal supported?

### ISSUE THREAD

**Issue by wceolin** [InfomediaLtd/angular2-materialize#134]
Is the [card-reveal](http://materializecss.com/cards.html#reveal) option working? If so, what attribute should I use to make it work?

**Comment by wceolin** [comment]
Hmm... My issue might be related to using a minified version of jQuery, as I'm getting that error referenced on #78 again.

Now I'm also having the same issue experienced by @bernhardwaidacher: if I use the minified version, I get `e.velocity is not a function`; if I use the non-minified version, then I get the `Cannot read property 'swing' of undefined` error.

**Comment by rubyboy** [comment]
@wceolin is it using JS? I think it's plain CSS, so it should be working without any special support.

I tried the following HTML (taken straight from the MaterializeCSS site) and it worked in my angular app:
```html
 <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="images/office.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
      <p><a href="#">This is a link</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
```

If you have a specific example that doesn't work please let us know. Otherwise, could you close the issue? Thanks.

**Comment by wceolin** [comment]
Hmm... It's not working, but it's probably some silly mistake I'm making because I just copied and pasted the code above and it worked.

In my case, I have something like this right now:

**card.html**

```
<div class="card" [ngSwitch]="params">
  <app-fruits *ngSwitchCase="'fruits'"></app-fruits>
  <app-vegetables *ngSwitchCase="'vegetables'"></app-vegetables>
</div>
```

**fruits.html**

```
<div [ngSwitch]="params.name" class="card-content">
  <div *ngSwitchCase="'orange'">
    <span class="card-title activator">Orange</span>
   <p>Some code here</p>
  </div>
</div>

<div class="card-reveal">
  <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
  <p>Here is some more information about this product that is only revealed once clicked on.</p>
</div>
```

Anyway, should I close it as it's not related to `angular2-materialize` itself?

**Comment by rubyboy** [comment]
Yes please. Thanks for the quick feedback.

On 16 Oct. 2016, at 4:07 pm, Will Ceolin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm... It's not working, but it's probably some silly mistake I'm making because I just copied and pasted the code above and it worked.

In my case, I have something like this right now:

card.html

<div class="card" [ngSwitch]="params">
  <app-fruits *ngSwitchCase="'fruits'"></app-fruits>
  <app-vegetables *ngSwitchCase="'vegetables'"></app-vegetables>
</div>


fruits.html

<div [ngSwitch]="params.name" class="card-content">
  <div *ngSwitchCase="'orange'">
    <span class="card-title activator">Orange</span>
   <p>Some code here</p>
  </div>
</div>

<div class="card-reveal">
  <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
  <p>Here is some more information about this product that is only revealed once clicked on.</p>
</div>


Anyway, should I close it as it's not related to angular2-materialize itself?

-
