### ISSUE TITLE
Two <select> are rendered one is materialize the other is normal

### ISSUE THREAD

**Issue by unaor** [InfomediaLtd/angular2-materialize#137]
i have the following html in my template
```
<div class="input-field">
   <select materialize="material_select" [materializeSelectOptions]="stationResults" (change) = "filterBy('result', $event.target.value)">
                     <option *ngFor="let result of stationResults" [value]="result">{{result}}</option>
              </select>
</div>
```
and for some reason two select elements are rendered, attaching screenshot
![bug](https://cloud.githubusercontent.com/assets/1891506/19403171/de376b2a-922a-11e6-817d-19f225f5f8e3.jpg)

**Comment by rubyboy** [comment]
@unaor can you share a repository that reproduces the problem? When trying the HTML you've pasted in the demo app it worked well.

**Comment by unaor** [comment]
sure @rubyboy 
https://github.com/unaor/angular2-materialize

just clone and ng serve and you would see it right away

**Comment by rubyboy** [comment]
@unaor the problem is with the following CSS you've added:
```html
select {
    display: block;
    height: inherit;
    border: none;
} 
```
If you remove the ```display: block``` there will only be one.

This will also happen when using vanilla MaterializeCSS. The way MaterializeCSS works is that it creates a different HTML for the selection box. The original "select" is actually being hidden and is only used as a "shadow" to the one you see.

I suggest either removing your styling or checking with the MaterializeCSS library how to style the newly created components.

**Comment by unaor** [comment]
thank you you were right ,and indeed can't figure how to override the library created components
