### ISSUE TITLE
materialize 0.97.8 changed API for Modals

### ISSUE THREAD

**Issue by pepperbob** [InfomediaLtd/angular2-materialize#150]
materialize changed the API for Modals slightly which breaks the integration in angular2-materialize.

https://github.com/Dogfalo/materialize/releases/tag/v0.97.8

![2016-10-31 13_14_28](https://cloud.githubusercontent.com/assets/1303743/19853834/049c6998-9f6c-11e6-8e87-dc78cc60a0bd.png)

![2016-10-31 13_16_39](https://cloud.githubusercontent.com/assets/1303743/19853948/a651ba0e-9f6c-11e6-8e9e-87cdcf55b0cd.png)

**Comment by rubyboy** [comment]
@pepperbob thanks for the heads up. It's actually been reported this morning (https://github.com/InfomediaLtd/angular2-materialize/issues/149) and a new version (6.0.0) of angular2-materialize has been released.
Are you able to grab the new version and confirm this is working properly for you? Thanks.
The example code in the app has also been updated to reflect the changes in Materialize. It's using MaterializeActions to trigger open/close: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts
```js
openModal() {
    this.modalActions.emit({action:"modal",params:['open']});
  }
  closeModal() {
    this.modalActions.emit({action:"modal",params:['close']});
  }
```

**Comment by pepperbob** [comment]
Oh, thanks for the quick reply - I couldn't find and issue about it - but I didn't expect it to be closed already! Will check it out. Thanks!

**Comment by jroehl** [comment]
i'm experiencing still problems when using the modals, even with angular2-materialize@6.0.0 and materialize-css@0.97.8:

when i'm implementing the modal like [https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts] nothing happens when i click the button.
when testing the modal with `$('#modalId').modal('open');` it throws an error `Uncaught TypeError: $overlay.velocity is not a function...`. i checked that the right jQuery version etc is installed but i can't fix this error.

does this belong to this issue, or should i open a new open? 

thanks in advance - and by the way - thanks for your awesome work!

**Comment by rubyboy** [comment]
@jroehl there are other issues related to the velocity error. It's related to your configs and how you import MaterializeCSS and jQuery. It depends on the type of config you have (Webpack, CLI, JSPM, etc.). Please search through the issues and maybe add your comments on the relevant ones that related to your specific config.
As a starting point I suggest cloning this repo and using the example app in there. The config of the example app is using JSPM (jspm install, live-server). If that works then it's surely related to how you configure your specific repo.

I'll close this issue for now unless anyone find specific issues related to the new version of MaterializeCSS and compatibility with angular2-materialize.
