### ISSUE TITLE
how i call Materialize.updateTextFields(); in my component

### ISSUE THREAD

**Issue by colombia9503** [InfomediaLtd/angular2-materialize#197]
I do not know how to call that method in my component to try to arrange that the labels do not overlap on the data 
Output:
![image](https://cloud.githubusercontent.com/assets/18128198/21456365/89af80ae-c8f5-11e6-81b0-00c14e81feec.png)
Expected output:
![image](https://cloud.githubusercontent.com/assets/18128198/21456376/a7850f4a-c8f5-11e6-8183-cb4979677349.png)

**Comment by rubyboy** [comment]
Hi @colombia9503 , are you trying to fix https://github.com/InfomediaLtd/angular2-materialize/issues/131 or https://github.com/InfomediaLtd/angular2-materialize/issues/106 ?
Because Materialize is globally available you could call it whenever you want and it should find Materialize on the window object.

**Comment by rubyboy** [comment]
See example here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/buttons.ts#L39

**Comment by colombia9503** [comment]
i'm trying to fix #131

**Comment by fontenele** [comment]
Look at https://github.com/Dogfalo/materialize/issues/180#issuecomment-74448008
They recommend add class 'active' on label. It works for me!!!

**Comment by samkojo** [comment]
Just call `Materialize.updateTextFields();`
