### ISSUE TITLE
Applying custom colors 

### ISSUE THREAD

**Issue by kootenpv** [InfomediaLtd/angular2-materialize#205]
Great job on this lib! I was wondering how to easily override the default color.

I have used sass to modify materialize.css, where I do set the `$secondary-color`, but how can I use this value in styles.css, for example to apply it to the background-color of `body`?

I understand it might be a bit off topic, but it is not really clear how to easily use basic materialize.css stuff other than the fancy stuff which is very nicely documented :)

**Comment by huug** [comment]
I tried to override the colors by adding the following lines to 'app.scss'

`
@import '~materialize-css/sass/components/variables';
$primary-color: #0E5A69 !default;
$primary-color-light: lighten($primary-color, 15%) !default;
$primary-color-dark: darken($primary-color, 15%) !default;
@import '~materialize-css/sass/materialize';
`

But that didn't work.

**Comment by maxmumford** [comment]
This depends on your setup somewhat but I'll tell you how I achieved customised variables with my project using the angular-cli.

- Follow all steps laid out in the [installation guide for ng2-cli w/ webpack](https://github.com/InfomediaLtd/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-angular-cliwebpack-100-beta26)
- Remove the following line from the styles array: `../node_modules/materialize-css/dist/css/materialize.css`
 - Open up src/styles.scss (if you only have src/style.css, rename it to style.scss and update the styles array in angular-cli.json accordingly)
 - Add the following lines:

```
$primary-color: #ff0000;
$roboto-font-path: "../node_modules/materialize-css/fonts/roboto/"; // fix font path
@import "node_modules/materialize-css/sass/materialize";
```

You've basically made it so instead of webpack importing the materialize css directly, you import it manually in styles.scss *after* overwriting some materialize variables.

Hope that helps

**Comment by marciomsm** [comment]
Hi @huug, did you override the colors? Could you please help me? Thanks.

**Comment by marciomsm** [comment]
It works for me:

- Remove the following line from the styles array: ../node_modules/materialize-css/dist/css/materialize.css
- Open up src/styles.scss (if you only have src/style.css, rename it to style.scss and update the styles array in angular-cli.json accordingly)
- Add the following lines:

`@import '~materialize-css/sass/components/color';
$secondary-color: color("blue", "darken-4");
$roboto-font-path: "~materialize-css/fonts/roboto/";
@import "~materialize-css/sass/materialize.scss";`

In this way I could change the colors theme.

**Comment by rubyboy** [comment]
Now there's sample code that @luketn added to the repo that overrides the colors: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/styles.scss
