### ISSUE TITLE
materialize chips selection is not working

### ISSUE THREAD

**Issue by imdivakar** [InfomediaLtd/angular2-materialize#246]
Hi @rubyboy 

[http://angular2-materialize.surge.sh/#/Chips](url) here if we add / delete a tag means i can able to see the details in console respectively but for selection of any tag i couldn't able to check the values in console can you please inspect it?

**Comment by rubyboy** [comment]
@imdivakar this is a bug in MaterializeCSS that was fixed only in the latest version (98): https://github.com/Dogfalo/materialize/commit/84f204db03ab24024dfcff95203b7b234c6a811b
I suggest up-voting the upgrade ticket to get this fix: https://github.com/InfomediaLtd/angular2-materialize/issues/221
We can keep this bug open until the other one gets resolved and we can verify that it's also fixed in angular2-materialize

**Comment by imdivakar** [comment]
Ok thanks

**Comment by rubyboy** [comment]
Looking good now, after the upgrade to v98. Get latest version of angular2-materialize (10).
