### ISSUE TITLE
How to disable all tooltips on mobile?

### ISSUE THREAD

**Issue by zilions** [InfomediaLtd/angular2-materialize#266]
Not too sure if it's best to ask here, or on the official Materialize repo.

But is there a way to disable all tooltips on mobiles? Tooltips do not work well on touch devices, and it would be good to disable tooltips globally for a set of rules.

**Comment by sergiobrr** [comment]
I'm looking for a way to disable tooltips in mobile too. No idea in how ti
accomplish this.

Il 07 mag 2017 12:59 PM, "Jade Mulholland" <notifications@github.com> ha
scritto:

Not too sure if it's best to ask here, or on the official Materialize repo.

But is there a way to disable all tooltips on mobiles? Tooltips do not work
well on touch devices, and it would be good to disable tooltips globally
for a set of rules.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/InfomediaLtd/angular2-materialize/issues/266>, or mute
the thread

**Comment by rubyboy** [comment]
I guess we could allow disabling the tooltip function programmatically, but I think this should be addressed in MaterializeCSS itself.
Here are a few related issues I could find:
- https://github.com/Dogfalo/materialize/issues/1141
- https://github.com/Dogfalo/materialize/issues/2158

**Comment by rubyboy** [comment]
Closing.
