### ISSUE TITLE
Webpage CSS turns non-responsive when modal is open and we try to change zoom %

### ISSUE THREAD

**Issue by Dsupreme** [InfomediaLtd/angular2-materialize#29]
When a modal is open and one tries to change the zoom % of the web page (Ctrl +, Ctrl -) the UI does not scale properly for the background webpage (modal scales properly).
Images:
Default (No Zoom)
http://prntscr.com/ayinq4,  http://prntscr.com/ayio1d (modal open)
Zoomed in
http://prntscr.com/ayiobj (Modal opened after zooming in)
http://prntscr.com/ayiott (Modal opened before zooming in)
 
Link for reference: 
https://github.com/Dsupreme/Ang2
(I setup a basic project. I documented all the steps in setting up such a project. Please follow the readme.md in case any concerns.)

**Comment by rubyboy** [comment]
@Dsupreme are you able to check if this is a MaterializeCSS problem or an angular2-materialize binding issue? You can do that by creating the same HTML and effect with plain HTML+MaterializeCSS and check if that happens there as well.

**Comment by rubyboy** [comment]
I've created https://github.com/InfomediaLtd/angular2-materialize/blob/master/index-materializecss.html for your convenience. Try pasting your example in there and see if it has the same problem. It it does, please create this issue in the https://github.com/Dogfalo/materialize repository. Otherwise, we can take a look at the binding and fix where necessary.
Thanks!

**Comment by Dsupreme** [comment]
It is a MaterializeCSS problem (Tested it out as suggested)
Created an issue in materialize repository.
https://github.com/Dogfalo/materialize/issues/3111

Can close this issue.
