### ISSUE TITLE
Demo not starting in IE11

### ISSUE THREAD

**Issue by mbeckenbach** [InfomediaLtd/angular2-materialize#58]
Hi, 

this project looks great but we need to support IE11. Materialize works when using IE11 but your demo page (http://angular2-materialize.surge.sh/) doesn't startup when using IE11.

MS Edge Browser works fine.

Two warnings, that can be easily fixed but one Error, that stops execution. As I can't read uglified code, the only thing i can give you for the moment is the error message.

**Warning**
- IE really hates a missing html5 doctype. Can cause quirks mode in some cases
DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>"

**Warning**
- IE does not like single quotes for HTML attributes. Simply replace <script src='index.js'></script> by <script src="index.js"></script>
Unexpected token. (angular2-materialize.surge.sh (2,1))

**Error**
SCRIPT438: Object doesn't support property or method 'keys'
index.js (45,290)

Same line with IE10, different error message
SCRIPT445: Object doesn't support this action
index.js (45,290)

Best regards

Max

**Comment by rubyboy** [comment]
@mbeckenbach thanks heaps for the tips.
If you'd like to dig further and submit a PR, most of the code for this wrapper is in a single file - https://github.com/InfomediaLtd/angular2-materialize/blob/master/src/materialize-directive.ts - and the little demo app is here - https://github.com/InfomediaLtd/angular2-materialize/tree/master/app .
Otherwise, I'll take a look in the next few weeks. We will require IE11 (actually IE9+) as well so it's definitely something that my company will need.
Cheers,
Ruby

**Comment by mbeckenbach** [comment]
OK the directive is surprisingly small. :-)
Let me see if i can find some time to dig into this in the next days.

**Comment by rubyboy** [comment]
You were right. The DOCTYPE was necessary. Also, the demo app didn't have ES6-shim.
Adding the two fixed it and I can now load it in IE11 successfully. I've deployed to http://angular2-materialize.surge.sh

Are you able to confirm so I can close this bug? Thanks.

**Comment by pchristou** [comment]
@rubyboy demo app works fine for me in IE11 now. Interestingly, the datepicker section throws the same error I'm experiencing as mentioned in #60

**Comment by rubyboy** [comment]
@pchristou thanks for checking. Datepicker is a different problem. I'm on it  😀
