### ISSUE TITLE
RC5 Compatibility

### ISSUE THREAD

**Issue by mcanatalay** [InfomediaLtd/angular2-materialize#81]
Hello,

As you know, modules are added in RC5. Currently, it supports the deprecated classes, but they plan to remove it in next RC.

Thank you.

**Comment by pchristou** [comment]
I second an update to RC5. It's been a fair while since an update has been made and it'd be good to be able to take advantage of modules.

**Comment by 7Kronos** [comment]
Forked it for RC-5 upgrade but I can't effectively test the app demo. I tested on an app npm installing it directly from git, seems to work fine. I can't finish the job properly because of the build system being incompatible with Windows !

[RC5 repo](https://github.com/7Kronos/angular2-materialize)

**Comment by rubyboy** [comment]
PR merged: https://github.com/InfomediaLtd/angular2-materialize/pull/86
Are you able to test that it all works for you with RC5?
Notice that the new version (5.0.0) has a breaking change of removing the dependency on materialize-css. This library will need to be imported separately.
Thanks.

**Comment by MehranMazhar** [comment]
its not working when i want to use it in 2 angular  module .
