### ISSUE TITLE
create multiple dropdowns using *ngFor

### ISSUE THREAD

**Issue by NishantDesai1306** [InfomediaLtd/angular2-materialize#94]
I have code in which i am creating multiple dropdowns using ngFor 

```
<div *ngFor="let item of items>
     <a materialize="dropdown" data-activates="{{'dropdown'+item._id}}">Drop me!</a>

     <ul id="{{copiedItem._id}}" class='dropdown-content'>
          <li>Option1</li>
          <li>Option2</li>
     </ul>
</div>

```

but as dropdown needs 
1. 'id' in dropdown (which i can handle by using id={{"dropdown"+item._id}} in ngFor i.e. generating different   ids like dropdown1, dropdown2, etc.)
2. 'data-activates' field in trigger (which i can`t handle because if i write data-activates="{{"dropdown+item._id}} then angular gives me error activates is not a native property")

I guess if one uses angular string interpolation in value of an attribute then angular requires that attribute to be some native attribute

Can't you implement eventEmitter in this directive as well just like the way you did it in modals and toasts ?

**Comment by whobeika** [comment]
@NishantDesai1306 did you ever get around this data-activates id issue?

**Comment by whobeika** [comment]
FYI, I ended up creating a custom directive for data-activates that fixed it. So now I can use interpolation and show multiple dropdowns in a ngFor for example...

**Comment by rubyboy** [comment]
@whobeika if you'd like to share your directive code or repo link here other people would appreciate it and could use that in their projects. Thanks!

**Comment by ryantehbaker** [comment]
+1

I'm running into this same issue and am in need of a solution.

**Comment by whobeika** [comment]
@rubyboy @ryantehbaker here you go...

[https://github.com/whobeika/angular2-materialize-extended](url)

I have tried several solutions including creating a custom directive to handle this. The simplest solution was to properly use the property binding on the anchor and tell angular that it's safe to use thus using [attr.data-activates] instead of data-activates will enable the interpolation and binding to go through correctly.

`<a class='dropdown-button btn' materialize="dropdown" data-beloworigin="true" [attr.data-activates]="'dropdown-'+item.id">{{item.title}}</a>`

@rubyboy maybe it is worth updating the documentation and showing an example for multiple dropdowns like so. Or if we can do something on the library side to support that it would be even better.

**Comment by rubyboy** [comment]
@whobeika thanks for sharing the code. I think the approach you've described is perfectly valid, using Angular's built-in support for interpolating in native attributes.
