### ISSUE TITLE
materializeParams problems with angular rc6

### ISSUE THREAD

**Issue by snarum** [InfomediaLtd/angular2-materialize#96]
After migrating from rc4 to rc6 I'm having problems with the materializeParams attribute:
systemjs parser gives:
    
    Can't bind to 'materializeParams' since it isn't a known property of 'a'

on the html:

`    <div class="col s2" >
        <a  materialize="leanModal" [materializeParams]="[{dismissible: false}]" class="waves-effect waves-light btn" href="#addUserModal"><i class="material-icons center">add</i></a>
    </div>`

I have inspected the html and can see that there has been som javascript magic on the "materialize" keyword, so I'm guessing that materialize-css.js has been run.

Any guesses as to what I am doing wrong?

**Comment by snarum** [comment]
I was just missing 

declarations: [  MaterializeDirective ], 

in my @NgModule

**Comment by rafaelzuckerberg** [comment]
Friend I have a problem please help me
where did you state MaterializeDirective, in the main Module or function module, because I don't understand, look I imported im my main module :
import { MaterializeModule } from 'angular2-materialize';

@NgModule({
  declarations: [
     ...
    MaterializeDirective
  ],
  imports: [
    ...
    MaterializeModule
  
  ],
})

where import MaterializeDirective ?????
